### PR TITLE
Add Feature: Map Function

### PR DESCRIPTION
**Pull request by Friendseeker**
Map is super useful and every lisp dialect has a map function, therefore I implemented this feature. I hope it makes a welcoming addition.

### CODE REVIEW

**Comment by ChesterJFGould** [comment]
I appreciate this addition, however only primitive forms should be added directly in the code. I do agree that some sort of standard library would be a nice addition so adding a way to include a file at startup containing a bunch of definitions would be a nice feature.

**Comment by ChesterJFGould** [comment]
Another thing to note if you are interested in this project is that I am considering just completely rewriting it as I believe it could be done in ~200 lines of Haskell instead of 2800 lines of Java.

**Comment by Friendseeker** [comment]
> I appreciate this addition, however only primitive forms should be added directly in the code. I do agree that some sort of standard library would be a nice addition so adding a way to include a file at startup containing a bunch of definitions would be a nice feature.

You should convince CPSC 110 staffs to replace DrRacket with your invention once you have the standard library support. Standard library should be super easy to implement considering the save/load feature is already there. 

> Another thing to note if you are interested in this project is that I am considering just completely rewriting it as I believe it could be done in ~200 lines of Haskell instead of 2800 lines of Java.

That would be really welcoming for learners like me! I had severe difficulty understanding the Java codebase for the project, and by having it with a FP language using fewer lines, the codebase would be much more readable!

**Comment by ChesterJFGould** [comment]
I don't know about replacing DrRacket with this as there would be a significant amount of work needed to be done to replicate all of its features and I personally have no interest in working on that. However if you would like to collaborate on a Haskell or other language version of this language please feel free to contact me at chestergould@protonmail.com and we can discuss details.

**Pull request closed without merging**
